spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    password: ''
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
